<div class="grid gap-2 lg:grid-cols-4">
    <flux:button
        variant="filled"
        icon="users"
        href="/Wibunity"
    >
        Wibunity
        <flux:badge
            size="sm"
            color="emerald"
        >
            Baru!
        </flux:badge>
    </flux:button>
    <flux:button
        variant="filled"
        icon="bookmark"
        href="/anime/bookmark"
    >
        Daftar Anime Saya
    </flux:button>
    <flux:button
        variant="filled"
        icon="calendar-date-range"
        href="/events"
    >
        Event Wibu
    </flux:button>
    <flux:button
        variant="filled"
        icon="newspaper"
        href="/news"
    >
        Berita Terbaru
    </flux:button>
    <flux:button
        variant="filled"
        icon="sparkles"
        href="/gacha"
        class="lg:col-span-4"
    >
        Gachamon
        <flux:badge
            size="sm"
            color="red"
        >
            Segera!
        </flux:badge>
    </flux:button>
</div>
